Try macOS-11 instead, since macOS-12 fails for some reason
It looks like things fail right after the Nix installation with:

```
/nix:
Error: unable to perform operation.  (-400)
	Error: unknown indexing state.
child_process.js:656
    throw err;
    ^

Error: Command failed: /Users/runner/work/_actions/cachix/install-nix-action/v13/lib/install-nix.sh
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at Object.<anonymous> (/Users/runner/work/_actions/cachix/install-nix-action/v13/lib/main.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1159,
  stdout: null,
  stderr: null
}
```

https://github.com/awakesecurity/proto3-suite/runs/7544965911?check_suite_focus=true

From a quick Google search, it looks like this is due to Spotlight
search not working on some external volumes (e.g. `/nix`) in MacOS
12:

https://macperformanceguide.com/blog/2022/20220205_2007-AppleCoreRot-Spotlight-FailedSearching.html

… so I'm working around this by downgrading to MacOS 11 for now.